### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by Aniket144** [maheshpaliwal/minovation#1]
## Progress Checklist 
- [x] Buying Domain.
- [x] Get Hosting.
- [x] Design Basic Backend (PHP).
- [ ] Set up a Counter/ComingUp Page as default.
- [x] Host the page.
- [ ] Build Basic FrontEnd.
    - Front Page 
    - Events Page (Separate Event Viewing Option)
    - Our Team Page
    - Registration Page
- [ ] Routing of Pages
- [ ] Registration (Backend)
- [ ] Payment Portal using php 
       - integrating Paytm '
          -- creating merchant account at Paytm
          -- deploying pay through paytm feature using paytm api
       - integrating debit cards
       
- [ ] Making Site Responsive
- [ ] Deploy

**Comment by maheshpaliwal** [comment]
issue resolved
